### ISSUE TITLE
Challenge Tracking

### ISSUE THREAD

**Issue by yupiel** [yupiel/helth-be#18]
As a User, I would like to set and track challenges for myself, so I can improve my health in a fun way.

- [x] Define Challenge Mode [ID, Activity Type, Amount of Times, length of challenge, start date, expriation date]
- [x] Define Challenge Status Enum in Challenge Model
- [x] Define schema in schema sql file
- [x] Define method in Challenge Repository Interface to track new challenge
- [x] Define data class for retrieved Challenge data
- [x] Implement method in Challenge Repository Locally to track new challenge
- [x] Define and Implement method in Challenge Service to track new challenge
- [x] Define and Implement track challenge endpoint
